#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
targetType=libso                            # Preferred library type
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
. $WM_PROJECT_DIR/wmake/scripts/have_boost
. $WM_PROJECT_DIR/wmake/scripts/have_zoltan

#------------------------------------------------------------------------------

wmake $targetType renumberMethods

warning="==> skip SloanRenumber"
if [ 0 -eq 1 ]
then
    wmake $targetType SloanRenumber || echo "$warning (build issues detected)"
else
    echo "$warning (no boost)"
fi


warning="==> skip zoltanRenumber"
if [ 0 -eq 1 ]
then
    wmake $targetType zoltanRenumber || echo "$warning (build issues detected)"
else
    echo "$warning (no library)"
fi

#------------------------------------------------------------------------------
